name: 28580_deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    needs: 28580_test
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t my-program:${{ github.sha }} .

      - name: Tag and push Docker image
        run: |
          docker tag my-program:${{ github.sha }} my-dockerhub-username/my-program:latest
          docker push my-dockerhub-username/my-program:latest